"""add deposit cascade and truck id

Revision ID: 150c5075353e
Revises: d0d1e2f3g4h7
Create Date: 2026-07-03 18:31:11.289909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '150c5075353e'
down_revision: Union[str, None] = 'd0d1e2f3g4h7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE invoices SET is_downloaded = 0 WHERE is_downloaded IS NULL")
    op.alter_column('invoices', 'is_downloaded',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.execute("UPDATE payroll_records SET is_downloaded = 0 WHERE is_downloaded IS NULL")
    op.alter_column('payroll_records', 'is_downloaded',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.add_column('vendor_topups', sa.Column('truck_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vendor_topups', 'vendor_trucks', ['truck_id'], ['id'])
    op.add_column('vendors', sa.Column('allow_deposit_cascade', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'allow_deposit_cascade')
    op.drop_constraint(None, 'vendor_topups', type_='foreignkey')
    op.drop_column('vendor_topups', 'truck_id')
    op.alter_column('payroll_records', 'is_downloaded',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('invoices', 'is_downloaded',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    # ### end Alembic commands ###
