"""Add is_downloaded column

Revision ID: 1ef964ef1a25
Revises: a9f3b2c1d8e7
Create Date: 2026-06-15 00:46:15.864371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1ef964ef1a25'
down_revision: Union[str, None] = 'a9f3b2c1d8e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('is_downloaded', sa.Boolean(), nullable=True))
    op.add_column('payroll_records', sa.Column('is_downloaded', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payroll_records', 'is_downloaded')
    op.drop_column('invoices', 'is_downloaded')
    # ### end Alembic commands ###
