"""Add soft delete and customer_id

Revision ID: 2b57c9f61d17
Revises: 89ca817d84a9
Create Date: 2026-06-03 21:30:13.292623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2b57c9f61d17'
down_revision: Union[str, None] = '89ca817d84a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('income_records', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_income_records_customer_id', 'income_records', 'customers', ['customer_id'], ['id'])
    
    op.add_column('invoices', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_invoices_customer_id', 'invoices', 'customers', ['customer_id'], ['id'])
    
    op.add_column('projects', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'is_active')
    op.drop_constraint('fk_invoices_customer_id', 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'customer_id')
    op.drop_constraint('fk_income_records_customer_id', 'income_records', type_='foreignkey')
    op.drop_column('income_records', 'customer_id')
    # ### end Alembic commands ###
