"""add_jasa_loading_models_and_fields

Revision ID: 2d3b8cb225f9
Revises: d395af295b68
Create Date: 2026-07-15 22:52:25.315348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d3b8cb225f9'
down_revision: Union[str, None] = 'd395af295b68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surat_jalan', sa.Column('loading_vendor_id', sa.Integer(), nullable=True))
    op.add_column('surat_jalan', sa.Column('loading_price', sa.DECIMAL(precision=15, scale=2), nullable=True))
    op.add_column('surat_jalan', sa.Column('loading_cost', sa.DECIMAL(precision=15, scale=2), nullable=True))
    op.create_foreign_key(None, 'surat_jalan', 'vendors', ['loading_vendor_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'surat_jalan', type_='foreignkey')
    op.drop_column('surat_jalan', 'loading_cost')
    op.drop_column('surat_jalan', 'loading_price')
    op.drop_column('surat_jalan', 'loading_vendor_id')
    # ### end Alembic commands ###
