"""update loading

Revision ID: 2d46d251290e
Revises: 2d3b8cb225f9
Create Date: 2026-07-18 01:37:23.419445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2d46d251290e'
down_revision: Union[str, None] = '2d3b8cb225f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_loading_prices', sa.Column('unit_type', sa.String(length=50), nullable=False))
    op.add_column('project_loading_prices', sa.Column('price', sa.DECIMAL(precision=15, scale=2), nullable=False))
    op.alter_column('project_loading_prices', 'project_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('project_loading_prices', 'price_per_unit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_loading_prices', sa.Column('price_per_unit', mysql.DECIMAL(precision=15, scale=2), nullable=False))
    op.alter_column('project_loading_prices', 'project_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('project_loading_prices', 'price')
    op.drop_column('project_loading_prices', 'unit_type')
    # ### end Alembic commands ###
