"""Add equipment rate history and hybrid logic

Revision ID: 2ed0a3d9d580
Revises: a1b2c3d4e5f6
Create Date: 2026-06-13 23:02:10.656996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2ed0a3d9d580'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # The table and indexes were already created in the partial execution
    # op.create_table('equipment_rate_history',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('equipment_id', sa.Integer(), nullable=False),
    # sa.Column('old_rate', sa.DECIMAL(precision=15, scale=2), nullable=True),
    # sa.Column('new_rate', sa.DECIMAL(precision=15, scale=2), nullable=False),
    # sa.Column('trigger_type', sa.String(length=30), nullable=False),
    # sa.Column('effective_date', sa.Date(), nullable=True),
    # sa.Column('status', sa.String(length=30), nullable=True),
    # sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    # sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    # sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_equipment_rate_history_equipment_id'), 'equipment_rate_history', ['equipment_id'], unique=False)
    # op.create_index(op.f('ix_equipment_rate_history_id'), 'equipment_rate_history', ['id'], unique=False)
    op.add_column('equipment', sa.Column('pending_rate_effective_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment', 'pending_rate_effective_date')
    op.drop_index(op.f('ix_equipment_rate_history_id'), table_name='equipment_rate_history')
    op.drop_index(op.f('ix_equipment_rate_history_equipment_id'), table_name='equipment_rate_history')
    op.drop_table('equipment_rate_history')
    # ### end Alembic commands ###
