"""Add project assignments and surat jalan

Revision ID: 2fe1c22d7b46
Revises: 2ed0a3d9d580
Create Date: 2026-06-14 11:41:11.460246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2fe1c22d7b46'
down_revision: Union[str, None] = '2ed0a3d9d580'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    if 'project_assignments' not in tables:
        op.create_table('project_assignments',
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('project_id', 'user_id')
        )
    
    if 'project_employees' not in tables:
        op.create_table('project_employees',
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column('employee_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('project_id', 'employee_id')
        )

    if 'surat_jalan' not in tables:
        op.create_table('surat_jalan',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column('field_staff_id', sa.Integer(), nullable=True),
        sa.Column('nopol', sa.String(length=50), nullable=True),
        sa.Column('nama_supir', sa.String(length=100), nullable=True),
        sa.Column('asal_tambang', sa.String(length=200), nullable=True),
        sa.Column('bruto', sa.Float(), nullable=True),
        sa.Column('tarra', sa.Float(), nullable=True),
        sa.Column('netto', sa.Float(), nullable=True),
        sa.Column('panjang', sa.Float(), nullable=True),
        sa.Column('lebar', sa.Float(), nullable=True),
        sa.Column('tinggi', sa.Float(), nullable=True),
        sa.Column('volume', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['field_staff_id'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )

    try:
        op.create_index(op.f('ix_surat_jalan_id'), 'surat_jalan', ['id'], unique=False)
    except Exception as e:
        print("Index already exists")
    
    # Check if column exists
    columns = [col['name'] for col in inspector.get_columns('projects')] if 'projects' in tables else []
    if 'measurement_type' not in columns:
        op.add_column('projects', sa.Column('measurement_type', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'measurement_type')
    op.drop_index(op.f('ix_surat_jalan_id'), table_name='surat_jalan')
    op.drop_table('surat_jalan')
    op.drop_table('project_employees')
    op.drop_table('project_assignments')
    # ### end Alembic commands ###
