"""Initial schema

Revision ID: 89ca817d84a9
Revises: 
Create Date: 2026-06-01 12:14:43.686015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '89ca817d84a9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'attendance', 'payroll_records', ['payroll_id'], ['id'])
    op.alter_column('fuel_prices', 'payment_status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               nullable=False,
               existing_server_default=sa.text("'unpaid'"))
    op.create_foreign_key(None, 'fuel_prices', 'users', ['paid_by'], ['id'])
    op.create_foreign_key(None, 'fuel_prices', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'income_records', 'invoices', ['invoice_id'], ['id'])
    op.create_foreign_key(None, 'payroll_records', 'projects', ['project_id'], ['id'])
    op.drop_constraint(op.f('fk_vendor_topups_equipment'), 'vendor_topups', type_='foreignkey')
    op.create_foreign_key(None, 'vendor_topups', 'equipment', ['equipment_id'], ['id'])
    op.create_foreign_key(None, 'vendor_topups', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vendor_topups', type_='foreignkey')
    op.drop_constraint(None, 'vendor_topups', type_='foreignkey')
    op.create_foreign_key(op.f('fk_vendor_topups_equipment'), 'vendor_topups', 'equipment', ['equipment_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'payroll_records', type_='foreignkey')
    op.drop_constraint(None, 'income_records', type_='foreignkey')
    op.drop_constraint(None, 'fuel_prices', type_='foreignkey')
    op.drop_constraint(None, 'fuel_prices', type_='foreignkey')
    op.alter_column('fuel_prices', 'payment_status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               nullable=True,
               existing_server_default=sa.text("'unpaid'"))
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    # ### end Alembic commands ###
