"""Add loading_rate to projects

Revision ID: d395af295b68
Revises: 150c5075353e
Create Date: 2026-07-15 22:27:21.657449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd395af295b68'
down_revision: Union[str, None] = '150c5075353e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('loading_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'loading_rate')
    # ### end Alembic commands ###
