"""add bank accounts and invoice bank relation

Revision ID: e456af295b69
Revises: 
Create Date: 2026-08-11 21:35:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e456af295b69'
down_revision = '1417da0795e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.engine.reflection import Inspector
    bind = op.get_context().bind
    inspector = Inspector.from_engine(bind)

    if 'bank_accounts' not in inspector.get_table_names():
        op.create_table('bank_accounts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('bank_name', sa.String(length=100), nullable=False),
        sa.Column('account_number', sa.String(length=100), nullable=False),
        sa.Column('account_name', sa.String(length=200), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True, default=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_bank_accounts_id'), 'bank_accounts', ['id'], unique=False)
    
    columns = [c['name'] for c in inspector.get_columns('invoices')]
    if 'bank_account_id' not in columns:
        with op.batch_alter_table('invoices', schema=None) as batch_op:
            batch_op.add_column(sa.Column('bank_account_id', sa.Integer(), nullable=True))
            batch_op.create_foreign_key('fk_invoices_bank_account_id', 'bank_accounts', ['bank_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint('fk_invoices_bank_account_id', type_='foreignkey')
        batch_op.drop_column('bank_account_id')

    op.drop_index(op.f('ix_bank_accounts_id'), table_name='bank_accounts')
    op.drop_table('bank_accounts')
    # ### end Alembic commands ###
